# Generated by Django 5.0.7 on 2024-12-09 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chargingstation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chargingstation',
            name='status',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='available_charging_points',
            field=models.IntegerField(default=True, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='connector_type',
            field=models.CharField(choices=[('Type1', 'Type 1 (SAE J1772)'), ('Type2', 'Type 2 (Mennekes)'), ('CCS', 'Combined Charging System (CCS)'), ('CHAdeMO', 'CHAdeMO'), ('Tesla', 'Tesla Connector')], default='Type2', max_length=20),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='is_operational',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='total_charging_points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
